Modification vote "Nouvelle Calédonie"
arnaudsm/votefinder.fr pull request #34
Opened 2024-06-29 08:55 UTC by Striffly

En référence à https://github.com/arnaudsm/votefinder.fr/issues/31

- Le texte n'indique en rien revenir sur l'accord de Nouméa
- Seule l'information du `sous_titre_1` semble pertinente à conserver, car le texte n'indique pas d'autres mesures "phares" que cette dernière

2024-06-29 17:52 UTC, arnaudsm requested changes
Le site a été designé pour 3 lignes obligatoirement, et vu la complexité de la situation une 3ème ligne est très important

On peut clarifier que le texte revient sur des promesses passées ? Ou tu as une autre idée ?

2024-06-30 03:29 UTC, Striffly commented
Comme l'expliquait @pep-un : "C'est dans ce sens que la mesure de gel du corps électoral fut mis en place, elle visait uniquement a assuré une stabilité du corps électoral durent la période de transition". Du coup je ne pense pas que cela revienne sur des promesses passés par rapport à cela.

La mise en place de cette mesure était en lien avec la tenue des référendums pour l'autodétermination, pour s'assurer que seuls les résidents ayant un lien historique et significatif avec la Nouvelle-Calédonie puissent participer à ces consultations cruciales.

Cependant, on peux citer que cela "Met fin au gel du corps électoral suite à la tenue des référendums d'autodétermination"

2024-06-30 04:07 UTC, pep-un commented
Bonjour, 

la situation est bien trop complexe pour être résumée en 3 lignes. 
Par exemple, la réforme ne remet pas en cause le corps électoral référendaire qui est un corps électoral spécial indépendant de celui des élections provinciales. 

De l'analyse juridique dominante, il n'y a pas de trahison des accords de Nouméa dans la réforme électorale. La crise est principalement politique, la méthode a été parfois décrite comme autoritaire pour des raisons multiples : d'une part les indépendantistes semblent refuser les négociations qui sont au point mort depuis le dernier référendum ; d'autre part toutes les évolutions de statut de la NC ce sont faite par accord locaux et non par réforme depuis la France ; le gouvernement espérait débloquer les négociations en réalisant une loi que les négociations local pouvaient renverser. Spoiler, ça n'a pas marché.

Très sincèrement, au vu de la complexité du sujet, du très important et complexe contexte, de son traitement médiatique catastrophique France, je ne sais pas si un sujet comme celui-là peux être résumée en trois ligne. 

Ils y a encore des dizaines d'autres points de contexte : culture kanak, crise du nickel, organisation politique locale, niveau d'autonomie, fonctionnement économique, force politique, géopolitique régionale du pacifique, ingérences étrangères, etc...

Quand je l'explique de manière sommaire à des proches il me faut entre 30min et 1h, alors 3 lignes...

2024-06-30 08:50 UTC, arnaudsm commented
@pep-un Je comprends la complexité, mais votefinder a une vocation de vulgarisation pour résumer la vie politique française aux personnes dépolitisées en quelques minutes. Nous n'avons pas vocation à faire du journalisme exhaustif, d'autres médias le font mieux.

Penses tu que nous pouvons trouver un compromis, on conseilles tu de retirer ce texte du site ?

2024-06-30 08:53 UTC, pep-un commented
Bonjour,
Je pense que la formation proposée dans le diff est la bonne.

2024-07-01 12:55 UTC, Striffly commented
Ok pour toi @arnaudsm ?

2024-07-03 01:05 UTC, arnaudsm approved these changes

2024-07-03 01:06 UTC, merged

2024-07-03 01:06 UTC, arnaudsm commented
Merci @pep-un, c'est déployé !